### ISSUE TITLE
avoid overflow

### ISSUE THREAD

**Issue by dalton5** [lpongetti/bubble_chart#4]
Hi,

First, thank you for this package. It's very useful.

I have this widget (code is below) which generates a number of bubbles with random radius.

It gives this:

![image](https://user-images.githubusercontent.com/8339768/126030144-23d7d9c9-2633-4087-a548-58ef23252072.png)

I have three questions:

1. How I can avoid the overflow and the semi circle. i need to show only full bubble.
2. What is the purpose of the number value in the leaf please?
3. How can I avoid to define a defined height for the chart?

Thanks,

    ` Widget generateBubbles(
          List<dynamic> list, double height, int bubbleSizeMin, int bubbleSizeMax) {
        Random random = Random();
        List<double> radius = List.generate(list.length, (int) {
          return (bubbleSizeMin + random.nextInt(bubbleSizeMax - bubbleSizeMin))
              .toDouble();
        });

    return SizedBox(
      width: Get.width,
      height: height,
      child: BubbleChartLayout(
          radius: (node) {
            var c = (node.options!.child as Container);
            return c.constraints!.maxHeight / 2 + 5;
          },
          root:
              BubbleNode.node(padding: 15, options: BubbleOptions(), children: [
            for (var i = 0;
                i < list.length;
                i++)
              BubbleNode.leaf(
                  value: 2000 + random.nextInt(13000),
                  options: BubbleOptions(
                      child: Container(
                          height: radius[i] * 2 - 20,
                          width: radius[i] * 2 - 20,
                          decoration: BoxDecoration(
                              borderRadius:
                                  BorderRadius.all(Radius.circular(radius[i])),
                              color: Colors.red)))),
          ])),
    );
  }`

**Comment by lpongetti** [comment]
Value is a number to represent the size respect to the other bubbles
It's better don't change radius

If you have a bubble with value: 1, it will take the maximum size, when you add more bubbles, they will all resize to fit the space but the bubble with value 10 will be 10 times bigger than the one with value 1
